# Generated by Django 3.2.3 on 2022-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='user_score',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
