# Generated by Django 3.2.3 on 2022-05-20 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_comment_content', models.CharField(max_length=100)),
                ('movie_comment_created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_comment_updated_at', models.DateTimeField(auto_now=True)),
                ('user_score', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='like_user',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_likes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='movie_likes', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='movies.Genre'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
