# Generated by Django 3.2.3 on 2022-05-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220520_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ariticle_content',
            new_name='article_content',
        ),
    ]
