# Generated by Django 3.2.3 on 2022-05-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_ariticle_content_article_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='article_user',
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='user',
            new_name='article_comment_user',
        ),
    ]
