# Generated by Django 3.2.3 on 2022-05-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220524_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='article_comment_user',
            new_name='user',
        ),
    ]
