# Generated by Django 3.2.3 on 2022-05-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20220526_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article_comment_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article_comment_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
